### Create a new report
POST http://localhost:3000/reports
content-type: application/json

{
    "make": "Vinfast",
    "model": "VF34",
    "year": 2020,
    "mileage": 12300,
    "lng": 0,
    "lat": 0,
    "price": 500000
}

### Approve an existing report
PATCH http://localhost:3000/reports/12
content-type: application/json

{
    "approved": true
}