### Create a new report
POST http://localhost:3000/reports
content-type: application/json

{
    "make": "Vinfast",
    "model": "VF34",
    "year": 2020,
    "mileage": 12300,
    "lng": 0,
    "lat": 0,
    "price": 0
}

### Approve an existing report
PATCH http://localhost:3000/reports/14
content-type: application/json

{
    "approved": true
}

### Get an estimate for an existing report
GET http://localhost:3000/reports?make=Vinfast&model=VF34&lng=0&lat=0&mileage=12300&year=2020